### ISSUE TITLE
[feat] Global recordings submit

### ISSUE THREAD

**Issue by MikkCZ** [pretalx/pretalx-youtube#3]
When inputting recordings for an event, it's currently necessary to input and submit them one by one, which makes the job really tedious. It would be great if one can fill all input fields for every talk and then save them all at once.

Better yet it would be to have YouTube API integration that would allow to select videos from some dropdown or soemthing, but that's probably out of scope of this plugin right now.

**Comment by rixx** [comment]
The plugin was changed  to a single form rather than one form per proposal back in c151851. This was released in v1.3.0, and is also included in the v2.0.0 release.

Please check the latest version of a plugin before feature requests, or at least include the version of the plugin you're using when making feature requests.

As for the YouTube API: That's a big request to drop in here, especially as the API is fickle and no fun. I can see myself building it if commissioned, or merge a PR to that extent, but would otherwise consider it out of scope (and better off in a separate issue, regardless).
