### ISSUE TITLE
No screenshots in README

### ISSUE THREAD

**Issue by justwheel** [pretalx/pretalx-youtube#5]
The README does not have any screenshots of what this plugin does and it is not immediately clear what distinguishes this plugin from uploading resources to a session. More visual formats would be helpful to understand why to use this plugin.

**Comment by rixx** [comment]
I feel like the difference is pretty clear in the description – it says that the plugin **embeds** videos on the talk page, rather than just linking to them.

Additionally, the README is not designed to convince people to use this plugin – if people want to use it, that's great, and if they are fine just linking to youtube videos in a way that speakers can control and modify, that's great, too.
